version: '3.3'

services:
  meal_mysql:
    container_name: meal-api-mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3360:3306
    environment:
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=db_password
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=db_user", "--password=db_password", "--host=127.0.0.1", "ping", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]

  meal_php:
    container_name: meal-api-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8040:8040"
      - "9040:9001"
    volumes:
      - .:/app:delegated
    depends_on:
      - meal_mysql
    command: symfony serve --dir=public --port=8040 --force-php-discovery

