controllers:
    resource: ../../src/*/Controller/
    type: annotation
    defaults:
        _format: json
#
#backoffice:
#    resource: ../../src/BackOffice/Controller/
#    type: annotation
#    defaults:
#        _format: json
#
#meal:
#    resource: ../../src/Meal/Api/
#    type: annotation
#    defaults:
#        _format: json
